<?php

namespace Database\Seeders;

use App\Models\House;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class HouseSeeder extends Seeder
{
    public function run()
    {



        DB::table('houses')->delete();

        DB::table('houses')->insert([
            0 => [
                'name' => 'shinig home',
                'price' => 5000,
                'payment_date' => Carbon::now(),
                'address' => 'CMC',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 2,
                'tenant_id' => 3,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            1 => [
                'name' => 'shinig home',
                'price' => 7000,
                'payment_date' => Carbon::now(),
                'address' => 'serp',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 5,
                'tenant_id' => 3,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            2 => [
                'name' => 'shinig home',
                'price' => 4000,
                'payment_date' => Carbon::now(),
                'address' => 'ayer dega',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 8,
                'tenant_id' => 3,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            3 => [
                'name' => 'shinig home',
                'price' => 3000,
                'payment_date' => Carbon::now(),
                'address' => 'Ayer hayl',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 2,
                'tenant_id' => 6,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            4 => [
                'name' => 'shinig home',
                'price' => 2000,
                'payment_date' => Carbon::now(),
                'address' => 'Harer kela',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 5,
                'tenant_id' => 9,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            5 => [
                'name' => 'shinig home',
                'price' => 7500,
                'payment_date' => Carbon::now(),
                'address' => '05',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 1,
                'owner_id' => 8,
                'tenant_id' => 10,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            6 => [
                'name' => 'shinig home',
                'price' => 3000,
                'payment_date' => Carbon::now(),
                'address' => '06',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => 'description goes here',
                // 'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 2,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            7 => [
                'name' => 'shinig home',
                'price' => 2000,
                'payment_date' => Carbon::now(),
                'address' => 'Gomata',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => 'description goes here',
                // 'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 2,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            8 => [
                'name' => 'shinig home',
                'price' => 1000,
                'payment_date' => Carbon::now(),
                'address' => 'CMC',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 5,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            9 => [
                'name' => 'shinig home',
                'price' => 5000,
                'payment_date' => Carbon::now(),
                'address' => 'sheikh nur hussen',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 8,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            10 => [
                'name' => 'shinig home',
                'price' => 1500,
                'payment_date' => Carbon::now(),
                'address' => 'sheikh nurhussen',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 5,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            11 => [
                'name' => 'shinig home',
                'price' => 4500,
                'payment_date' => Carbon::now(),
                'address' => 'CMC',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 2,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            12 => [
                'name' => 'shinig home',
                'price' => 5000,
                'payment_date' => Carbon::now(),
                'address' => '04',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 8,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            13 => [
                'name' => 'shinig home',
                'price' => 5000,
                'payment_date' => Carbon::now(),
                'address' => 'serp',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 8,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ],
            14 => [
                'name' => 'shinig home',
                'price' => 5000,
                'payment_date' => Carbon::now(),
                'address' => 'Ayer hayl',
                'area' => 254,
                'rooms' => 4,
                'latitude' => 9.343141136397598,
                'longitude' => 42.81584220190586,
                'description' => "<p>This adaptable living space is designed for creativity and personalization offering blank-canvas rooms that can transform to fit your lifestyle. The open layout provides large airy areas with neutral walls and durable flooring ideal for configuring as bedrooms workspaces\, or lounges based on your needs. Natural light floods the space through well-placed windows enhancing its versatility for any use. The property includes multiple unassigned rooms each with electrical outlets heating and ventilation ready to be furnished or repurposed. A central common area connects the spaces allowing for easy flow between zones. The simplicity of the design encourages renters to imprint their own style whether for living working or creative projects.Situated in a practical location the house is close to transit and essential services while maintaining a quiet atmosphere. With no predefined room functions you are free to define the space—turn one room into a studio another into storage or whatever suits your needs. Minimal restrictions mean maximum freedom to make it yours</p>",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'rented' => 0,
                'owner_id' => 2,
                'tenant_id' => NULL,
                'privateNotes' => NULL,
                'amenities' => NULL,
            ]
        ]);

        $houses = House::all();

        foreach ($houses as $house) {
            for ($i = 1; $i <= 5; $i++) {
                $house->addMedia(storage_path('temp\housepic' . $i. ' - Copy ('.$house->id.').jpg'))
                    ->toMediaCollection('images');
            }
        }

    }
}